# ----
# Site

title: Setup Guide
url: "https://robisaacnz.github.io/view-source/"
baseurl:
google_analytics_key:
show_full_navigation: false

logo: /siteicon.png
description: A complete guide to installing and configuring the tools we use at Figure.NZ.
author:
  name:
  email:
  twitter: figurenz
social:
  name: Figure.NZ Setup Guide
  links:
    - https://robisaacnz.github.io/view-source/

# -----
# Build

permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
